In [2]:
import numpy as np

 List vs Numpy

In [20]:
from time import process_time
python_list = [i for i in range(1000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.00022952499999995268


In [21]:
np_array = np.array([i for i in range(1000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.00014060400000026618


Numpy array

In [2]:
# List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [4]:

import numpy as np
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)



[1 2 3 4 5]


numpy.ndarray

 Creating a one dimenstional array

In [8]:
a = np.array([1,2,3,4])
print(a)
a.shape
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

Intial placeholders in numpy array

Creating a numpy array of zeros

In [12]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Create numpy array of ones

In [13]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array of particular value

In [15]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Create an identity matrix(same number of rows and columns)

In [16]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create a numpy array with random values

In [18]:
b = np.random.random((3,4))
print(b)

[[0.84969213 0.08615679 0.98153179 0.76194933]
 [0.08432883 0.98770456 0.66160215 0.12893153]
 [0.03240163 0.80022213 0.66891502 0.25906634]]


Random Integer values array with specific range

In [19]:
c = np.random.randint(10,100,(3,5))
print(c)

[[48 38 50 55 34]
 [92 77 79 70 16]
 [99 78 39 74 76]]


array of evenly spaced values(specifying the no. of values required)

In [20]:
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


array of evenly spaced values(specifying the step value)

In [21]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


Converting List to nparray

In [23]:
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analyzing Numpy array

In [24]:
c = np.random.randint(10,90,(5,5))
print(c)

[[35 71 56 62 42]
 [13 51 56 16 71]
 [21 49 22 31 73]
 [22 12 58 75 65]
 [61 59 27 42 89]]


Array Dimension

In [25]:
print(c.shape)
print(c.ndim)

(5, 5)
2


Number of elements in an array

In [26]:
print(c.size)

25


Checking data type of the values in array

In [29]:
print(c.dtype)

int64


Mathematical Operations on numpy array



Concatenating or joining two lists

In [30]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


For Numpy it is diffrent lets see

In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[7 8 9]
 [9 5 7]
 [1 4 0]]
[[17 18 19]
 [16 11 14]
 [13 15 19]]
[[24 26 28]
 [25 16 21]
 [14 19 19]]
[[-10 -10 -10]
 [ -7  -6  -7]
 [-12 -11 -19]]
[[119 144 171]
 [144  55  98]
 [ 13  60   0]]
[[0.41176471 0.44444444 0.47368421]
 [0.5625     0.45454545 0.5       ]
 [0.07692308 0.26666667 0.        ]]


In [33]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[24 26 28]
 [25 16 21]
 [14 19 19]]
[[-10 -10 -10]
 [ -7  -6  -7]
 [-12 -11 -19]]
[[119 144 171]
 [144  55  98]
 [ 13  60   0]]
[[0.41176471 0.44444444 0.47368421]
 [0.5625     0.45454545 0.5       ]
 [0.07692308 0.26666667 0.        ]]


Array Manipulation

Array manipulation refers to the process of changing the shape, structure, content, or arrangement of arrays in programming

In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 5 6]
 [7 3 3]]
(2, 3)


Transpose

In [35]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[3 7]
 [5 3]
 [6 3]]
(3, 2)


In [37]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 8 1]
 [3 7 6]]
(2, 3)


Another method for transposing

In [38]:
trans2 = array.T
print(trans2)
print(trans2.shape)


[[4 3]
 [8 7]
 [1 6]]
(3, 2)


Reshaping array

In [41]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 5 4]
 [5 0 1]]
(2, 3)
[[6 5]
 [4 5]
 [0 1]]
(3, 2)
